### ISSUE TITLE
Cool!

### ISSUE THREAD

**Issue by naxIO** [kexo1/LELDOOM#1]
Will it feature multiplayer at some point?

If so check Mirror for Unity: https://mirror-networking.com/

Free and Opensource since 2014.

**Comment by kexo1** [comment]
Thank you for positive feedback! About mutiplayer - I personally don't have that much time to spend on this project, it's my first game and it has messy code, so I think it wouldn't fit into this game. But maybe in future I will make another game that will have multiplayer :)
